server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    location /api/ {
        proxy_pass http://backend:5000/api/;
        # Tell backend the original URL the browser requested (not nginx's internal one), tells which site the user wants
        proxy_set_header Host $host;
        # Tell backend the real client IP, For logging who accessed what, rate-limiting by IP, or blocking bad actors
        proxy_set_header X-Real-IP $remote_addr;
        # Pass the full chain of IPs the request traveled through
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Tell backend whether original request was HTTP or HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
